import React, { useState, useCallback, useEffect } from 'react';
import { Handle, Position, NodeResizer, useReactFlow } from '@xyflow/react';
import { toast } from '../ui/use-toast';
import { Zap, Activity, Settings, RotateCcw, Save, Send } from 'lucide-react';
import { NodeNameHeader } from '../ui/node-name-header';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Textarea } from '../ui/textarea';
import { Slider } from '../ui/slider';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Progress } from '../ui/progress';
import { Collapsible, CollapsibleContent } from '../ui/collapsible';
import { aiNodesService, type AINodeConfig } from '@/services/aiNodesService';

interface GroqLlamaNodeProps {
  id: string;
  data: {
    label: string;
    description: string;
    status: 'idle' | 'running' | 'completed' | 'error';
    inputData?: NodeOutputData; // Data from connected nodes
    outputData?: any;
    onDataOutput?: (data: any) => void;
    onStatusChange?: (status: 'idle' | 'running' | 'completed' | 'error') => void;
    onOutputDataChange?: (outputData: any) => void;
    isWorkflowExecution?: boolean;
  };
  selected?: boolean;
}

interface NodeOutputData {
  type?: string;
  text?: string;
  content?: string;
  metadata?: Record<string, any>;
}

const groqModels = [
  { value: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B Instant' },
  { value: 'llama-3.1-405b-reasoning', label: 'Llama 3.1 405B Reasoning' },
  { value: 'mixtral-8x7b-32768', label: 'Mixtral 8x7B' },
  { value: 'gemma2-9b-it', label: 'Gemma 2 9B IT' },
  { value: 'llama3-groq-70b-8192-tool-use-preview', label: 'Llama 3 Groq 70B Tool Use' },
  { value: 'llama3-groq-8b-8192-tool-use-preview', label: 'Llama 3 Groq 8B Tool Use' },
];

const GCAL_EVENT_PROMPT = `You are a calendar event creator. Output ONLY a JSON object in this exact format:
{
  "summary": "Event Title",
  "description": "Generated by AI: Event details",
  "start": {
    "dateTime": "2025-07-02T14:00:00",
    "timeZone": "America/Los_Angeles"
  },
  "end": {
    "dateTime": "2025-07-02T15:00:00",
    "timeZone": "America/Los_Angeles"
  }
}

Rules:
1. Use future dates only
2. Default to 1-hour duration
3. Add "Generated by AI: " prefix to description
4. Output ONLY the JSON, no other text`;

const GMAIL_DRAFT_PROMPT = `You are an email drafter. Output ONLY a JSON object in this exact format:
{
  "to": "recipient@example.com",
  "subject": "Email Subject",
  "body": "The full body of the email goes here."
}

Rules:
1. The 'to' field must be a valid email address.
2. The 'subject' and 'body' fields are strings.
3. Output ONLY the JSON, no other text.`;

const defaultConfig: AINodeConfig = {
  model: 'llama-3.1-8b-instant',
  temperature: 0.7,
  max_tokens: 1000,
  system_prompt: 'You are a helpful AI assistant.',
  user_prompt: 'Please analyze the following:'
};

const GroqLlamaNode: React.FC<GroqLlamaNodeProps> = ({ id, data, selected }) => {
  const [showConfig, setShowConfig] = useState(false);
  const [config, setConfig] = useState<AINodeConfig>(defaultConfig);
  const [apiKey, setApiKey] = useState('');
  const [isExecuting, setIsExecuting] = useState(false);
  const [executionProgress, setExecutionProgress] = useState(0);
  const [, setIsOutputExpanded] = useState(false);
  const [localStatus, setLocalStatus] = useState<'idle' | 'running' | 'completed' | 'error'>('idle');
  const [localOutputData, setLocalOutputData] = useState<any>(null);
  const [executionCost] = useState<number | null>(null);
  const [usage, setUsage] = useState<any>(null);
  const [isInputReady, setIsInputReady] = useState(false);

  // Add React Flow hooks to detect connected nodes
  useReactFlow();

  // Effect to update config when document data is received via props
  useEffect(() => {
    if (data.inputData && data.inputData.type === 'document_processed') {
      const newPrompt = data.inputData.text || '';
      
      if (config.user_prompt !== newPrompt) {
        console.log('📄 Document data received via props, pasting into user prompt.');
        const newConfig = { ...config, user_prompt: newPrompt };
        setConfig(newConfig);
        
        aiNodesService.updateAINodeConfig('groqllama', newConfig)
          .then(() => console.log('✅ Backend Groq config updated with document text.'))
          .catch(error => console.error('❌ Failed to update backend Groq config:', error));
      }
    }
  }, [data.inputData, config]); // Depend on inputData

  // Use local state if data props aren't provided
  const currentStatus = data.status || localStatus;
  const currentOutputData = data.outputData || localOutputData;

  const getStatusColor = () => {
    switch (currentStatus) {
      case 'running': return 'border-purple-400/60 bg-purple-500/10';
      case 'completed': return 'border-green-400/60 bg-green-500/10';
      case 'error': return 'border-red-400/60 bg-red-500/10';
      default: return 'border-purple-400/40 bg-purple-900/20';
    }
  };

  const updateStatus = useCallback((status: 'idle' | 'running' | 'completed' | 'error') => {
    setLocalStatus(status);
    data.onStatusChange?.(status);
  }, [data.onStatusChange]);

  const updateOutputData = useCallback((outputData: any) => {
    setLocalOutputData(outputData);
    data.onOutputDataChange?.(outputData);
  }, [data.onOutputDataChange]);

  // Load configuration on mount
  useEffect(() => {
    const loadConfig = async () => {
      try {
        const response = await aiNodesService.getAINodeConfig('groqllama');
        if (response.success && response.config) {
          setConfig(response.config);
        }
      } catch (error) {
        console.warn('Could not load saved config, using defaults');
      }
    };

    // Load saved API key
    const savedApiKey = localStorage.getItem('groqllama_api_key');
    if (savedApiKey) {
      setApiKey(savedApiKey);
    }

    loadConfig();
  }, []);

  const handleConfigChange = useCallback((key: keyof AINodeConfig, value: any) => {
    setConfig(prev => ({ ...prev, [key]: value }));
  }, []);

  const handleApiKeyChange = useCallback((value: string) => {
    setApiKey(value);
    // Save to localStorage for persistence
    if (value) {
      localStorage.setItem('groqllama_api_key', value);
    } else {
      localStorage.removeItem('groqllama_api_key');
    }
  }, []);

  const saveConfig = useCallback(async () => {
    try {
      console.log('🔧 Saving Groq config:', config);
      await aiNodesService.updateAINodeConfig('groqllama', config);
      console.log('✅ Groq config saved successfully');
    } catch (error) {
      console.error('❌ Failed to save config:', error);
      alert('Failed to save configuration. Please try again.');
    }
  }, [config]);

  const resetConfig = useCallback(() => {
    setConfig(defaultConfig);
  }, []);

  // Update effect to handle input data changes
  useEffect(() => {
    if (data.inputData) {
      console.log('📥 Groq node received input data:', data.inputData);
      // Update config with input data
      const newConfig = {
        ...config,
        user_prompt: typeof data.inputData === 'string' 
          ? data.inputData 
          : data.inputData?.content || data.inputData?.text || ''
      };
      setConfig(newConfig);
      setIsInputReady(true);
    }
  }, [data.inputData]);

  // Update workflow execution effect to wait for input
  useEffect(() => {
    const shouldExecute = 
      data.isWorkflowExecution && // Is part of workflow execution
      !isExecuting && // Not already executing
      currentStatus === 'idle' && // In idle state
      isInputReady && // Has received input data
      config.user_prompt; // Has a prompt to execute

    if (shouldExecute) {
      console.log('🔄 Workflow execution detected, input ready, auto-executing Groq...', {
        isWorkflowExecution: data.isWorkflowExecution,
        isExecuting,
        currentStatus,
        isInputReady,
        hasPrompt: Boolean(config.user_prompt)
      });
      
      // Add small delay to ensure UI is updated
      setTimeout(() => {
        handleExecute();
      }, 500);
    }
  }, [data.isWorkflowExecution, isExecuting, currentStatus, isInputReady, config.user_prompt]);

  // Update handleExecute to log more info
  const handleExecute = useCallback(async () => {
    if (isExecuting) return;
    
    let progressInterval: NodeJS.Timeout | null = null;
    
    try {
      console.log('🚀 Starting Groq execution:', {
        model: config.model,
        prompt: config.user_prompt,
        isWorkflowExecution: data.isWorkflowExecution,
        inputData: data.inputData
      });

      setIsExecuting(true);
      updateStatus('running');
      setExecutionProgress(0);
      
      // Start progress animation
      progressInterval = setInterval(() => {
        setExecutionProgress(prev => Math.min(prev + 5, 90));
      }, 500);

      console.log('🚀 Executing Groq node:', {
        model: config.model,
        prompt: config.user_prompt,
        isWorkflowExecution: data.isWorkflowExecution
      });

      const userContent = config.user_prompt || 'Please provide a helpful response.';
      
      const model = groqModels.find(m => m.value === config.model) ? config.model : 'llama-3.1-8b-instant';
      
      const requestBody = {
         model,
         messages: [
           { role: 'system', content: config.system_prompt },
           { role: 'user', content: userContent }
         ],
        temperature: config.temperature,
        max_tokens: config.max_tokens
      };

      console.log('📤 Direct Groq API request:', { model, temperature: config.temperature, max_tokens: config.max_tokens });

      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(requestBody)
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`Groq API error: ${errorData.error?.message || response.statusText}`);
      }

      const responseData = await response.json();
      console.log('✅ Direct Groq API response received');
      
      const content = responseData.choices[0]?.message?.content || 'No response generated';
      
      updateOutputData({
        content,
        model: responseData.model,
        usage: responseData.usage,
        timestamp: new Date().toISOString()
      });
      
      setUsage(responseData.usage);
      updateStatus('completed');

      if (progressInterval) {
        clearInterval(progressInterval);
      }
      setExecutionProgress(100);
      
      setTimeout(() => {
        setExecutionProgress(0);
        setIsOutputExpanded(true);
      }, 1000);

    } catch (error) {
      console.error('❌ GroqLlama execution failed:', error);
      if (progressInterval) {
        clearInterval(progressInterval);
      }
      updateStatus('error');
      setExecutionProgress(0);
      
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      alert(`Execution failed: ${errorMessage}`);
    } finally {
      setIsExecuting(false);
    }
  }, [id, config, apiKey, isExecuting, updateStatus, updateOutputData]);

  const handleSendToNext = useCallback(() => {
    if (currentOutputData && data.onDataOutput) {
      const isCalendarEvent = config.system_prompt === GCAL_EVENT_PROMPT;
      const isEmailDraft = config.system_prompt === GMAIL_DRAFT_PROMPT;

      if (isCalendarEvent) {
        // Parse the content as JSON if it's a string and looks like JSON
        let parsedContent;
        try {
          parsedContent = typeof currentOutputData.content === 'string' 
            ? JSON.parse(currentOutputData.content)
            : currentOutputData.content;
            
          // Validate that it's a calendar event
          if (!parsedContent.summary || !parsedContent.start || !parsedContent.end) {
            throw new Error('Invalid calendar event format');
          }

          // Send the calendar event data
          data.onDataOutput({
            type: 'groq_processed',
            content: parsedContent,
            metadata: {
              ...currentOutputData.metadata,
              isCalendarEvent: true,
              source: 'groq'
            },
            model: currentOutputData.model,
            provider: 'groq'
          });
          
          console.log('📤 Sent calendar event data to next node:', parsedContent);
          
          toast({
            title: "Calendar Event Data Sent",
            description: "Calendar event data sent to Google Calendar node",
          });
        } catch (e) {
          console.error('❌ Failed to parse Groq output as calendar event:', e);
          toast({
            title: "Error",
            description: "The Groq output is not in valid calendar event format",
            variant: "destructive",
          });
          return;
        }
      } else if (isEmailDraft) {
        // Handle Email Draft
        let parsedContent;
        try {
          parsedContent = typeof currentOutputData.content === 'string' 
            ? JSON.parse(currentOutputData.content)
            : currentOutputData.content;
            
          // Validate that it's an email draft
          if (!parsedContent.to || !parsedContent.subject || typeof parsedContent.body === 'undefined') {
            throw new Error('Invalid email draft format. Required fields: to, subject, body.');
          }

          // Send the email draft data
          data.onDataOutput({
            type: 'groq_processed',
            content: parsedContent,
            metadata: {
              ...currentOutputData.metadata,
              isEmailDraft: true,
              source: 'groq'
            },
            model: currentOutputData.model,
            provider: 'groq'
          });
          
          console.log('📤 Sent email draft data to next node:', parsedContent);
          
          toast({
            title: "Email Draft Data Sent",
            description: "Email draft data sent to the next node.",
          });
        } catch (e) {
          console.error('❌ Failed to parse Groq output as email draft:', e);
          toast({
            title: "Error",
            description: e instanceof Error ? e.message : "The Groq output is not in a valid email draft format.",
            variant: "destructive",
          });
          return;
        }
      } else {
        // Handle regular non-calendar data
        data.onDataOutput({
          type: 'groq_processed',
          content: currentOutputData.content,
          metadata: currentOutputData.metadata,
          model: currentOutputData.model,
          provider: 'groq'
        });
        
        toast({
          title: "Data Sent",
          description: "Data sent to next node",
        });
      }
    }
  }, [currentOutputData, data.onDataOutput, config.system_prompt]);

  const truncateText = (text: string, maxLength: number = 1000) => {
    if (!text) return 'No content';
    if (text.length <= maxLength) return text;
    
    // Try to truncate at the last complete sentence
    const truncated = text.substring(0, maxLength);
    const lastPeriod = truncated.lastIndexOf('.');
    const lastQuestion = truncated.lastIndexOf('?');
    const lastExclamation = truncated.lastIndexOf('!');
    
    const lastSentenceEnd = Math.max(lastPeriod, lastQuestion, lastExclamation);
    
    if (lastSentenceEnd > maxLength * 0.8) {
      return text.substring(0, lastSentenceEnd + 1) + ' ...';
    }
    
    return truncated + ' ...';
  };

  return (
    <div 
      className={`relative min-w-[350px] min-h-[350px] backdrop-blur-xl border-2 rounded-xl p-4 shadow-lg ${getStatusColor()} ${selected ? 'ring-2 ring-purple-400/50' : ''}`}
    >
      {/* Node Resizer */}
      <NodeResizer 
        color="#a855f7" 
        isVisible={selected}
        minWidth={350}
        minHeight={350}
      />
      
      {/* Background Gradient */}
      <div className="absolute inset-0 bg-gradient-to-br from-purple-500/10 via-violet-500/5 to-purple-600/10 rounded-xl" />
      
      {/* Content */}
      <div className="relative z-10 h-full flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center space-x-3 flex-1 min-w-0">
            <div className="p-2 rounded-lg bg-gradient-to-br from-purple-400/30 to-violet-400/30 backdrop-blur-sm border border-purple-400/40">
              <Zap className="w-5 h-5 text-purple-300" />
            </div>
            <div className="flex-1 min-w-0">
              <NodeNameHeader
                nodeId={id}
                originalLabel={data.label}
                className="mb-0"
              >
                {currentStatus === 'running' && (
                  <Activity className="w-4 h-4 text-purple-400" />
                )}
              </NodeNameHeader>
              <p className="text-xs text-purple-200/70 truncate">{data.description}</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-2">
            <Button
              onClick={() => setShowConfig(!showConfig)}
              size="sm"
              variant="ghost"
              className="h-8 w-8 p-0 text-purple-300 hover:text-purple-200 hover:bg-purple-400/20"
            >
              <Settings className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* Configuration Panel */}
        <Collapsible
          open={showConfig}
          onOpenChange={setShowConfig}
          className="mb-4 transition-all duration-300 ease-in-out"
        >
          <CollapsibleContent className="data-[state=open]:animate-slideDown data-[state=closed]:animate-slideUp">
            <div className="space-y-3 p-3 bg-slate-900/50 border border-purple-400/20 rounded">
              <div className="flex items-center justify-between">
                <h4 className="text-sm font-medium text-purple-200">Configuration</h4>
                <div className="flex space-x-2">
                  <Button onClick={saveConfig} size="sm" variant="ghost" className="h-7 px-2 text-xs">
                    <Save className="w-3 h-3 mr-1" />
                    Save
                  </Button>
                  <Button onClick={resetConfig} size="sm" variant="ghost" className="h-7 px-2 text-xs">
                    <RotateCcw className="w-3 h-3 mr-1" />
                    Reset
                  </Button>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="col-span-2">
                  <label className="text-xs text-purple-300 font-medium">Model</label>
                  <Select value={config.model} onValueChange={(value) => handleConfigChange('model', value)}>
                    <SelectTrigger className="h-8 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {groqModels.map((model) => (
                        <SelectItem key={model.value} value={model.value} className="text-xs">
                          {model.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <label className="text-xs text-purple-300 font-medium">Temperature: {config.temperature}</label>
                  <Slider
                    value={[config.temperature]}
                    onValueChange={([value]) => handleConfigChange('temperature', value)}
                    max={2}
                    min={0}
                    step={0.1}
                    className="mt-1"
                  />
                </div>

                <div>
                  <label className="text-xs text-purple-300 font-medium">Max Tokens</label>
                  <Input
                    type="number"
                    value={config.max_tokens}
                    onChange={(e) => handleConfigChange('max_tokens', parseInt(e.target.value))}
                    className="h-8 text-xs"
                    min={1}
                    max={8192}
                  />
                </div>

                <div className="col-span-2">
                  <label className="text-xs text-purple-300 font-medium">API Key (optional)</label>
                  <Input
                    type="password"
                    placeholder="Enter Groq API key..."
                    value={apiKey}
                    onChange={(e) => handleApiKeyChange(e.target.value)}
                    className="h-8 text-xs"
                  />
                </div>

                <div className="col-span-2">
                  <div className="flex items-center justify-between mb-2">
                    <label className="text-xs text-purple-300 font-medium">System Prompt</label>
                    <Select
                      onValueChange={(value) => {
                        if (value === 'gcal_event') {
                          handleConfigChange('system_prompt', GCAL_EVENT_PROMPT);
                        } else if (value === 'gmail_draft') {
                          handleConfigChange('system_prompt', GMAIL_DRAFT_PROMPT);
                        } else {
                          handleConfigChange('system_prompt', defaultConfig.system_prompt);
                        }
                      }}
                    >
                      <SelectTrigger className="h-7 text-xs w-48">
                        <SelectValue placeholder="Select template" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="gcal_event" className="text-xs">Create Calendar Event</SelectItem>
                        <SelectItem value="gmail_draft" className="text-xs">Draft Gmail Email</SelectItem>
                        <SelectItem value="custom" className="text-xs">Custom</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <Textarea
                    value={config.system_prompt}
                    onChange={(e) => handleConfigChange('system_prompt', e.target.value)}
                    placeholder="System instructions for the AI..."
                    className="text-xs h-16 resize-none"
                  />
                </div>

                <div className="col-span-2">
                  <label className="text-xs text-purple-300 font-medium">User Prompt</label>
                  <Textarea
                    value={config.user_prompt}
                    onChange={(e) => handleConfigChange('user_prompt', e.target.value)}
                    placeholder="Connect a node or paste text here..."
                    className="text-xs h-24 resize-none"
                  />
                </div>
              </div>
            </div>
          </CollapsibleContent>
        </Collapsible>

        {/* Main Content Area - Flex grow to fill space */}
        <div className="flex-grow flex flex-col justify-between space-y-4">
          {/* Execute Section */}
          <div className="space-y-3">
            {/* Progress */}
            {executionProgress > 0 && (
              <div className="space-y-1">
                <Progress value={executionProgress} className="h-1" />
                <p className="text-xs text-purple-200/70 text-right">{executionProgress}%</p>
              </div>
            )}

            {/* Execute Button */}
            <Button
              onClick={handleExecute}
              className="w-full bg-purple-500/20 hover:bg-purple-500/30 text-purple-200"
              disabled={currentStatus === 'running' || !apiKey}
            >
              {currentStatus === 'running' ? 'Processing...' : 'Execute with Groq'}
            </Button>

            {/* Test API Key Button */}
            {apiKey && (
              <Button
                onClick={async () => {
                  try {
                    console.log('🧪 Testing API key...');
                    const testResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
                      method: 'POST',
                      headers: {
                        'Authorization': `Bearer ${apiKey}`,
                        'Content-Type': 'application/json'
                      },
                      body: JSON.stringify({
                        model: 'llama-3.1-8b-instant',
                        messages: [{ role: 'user', content: 'Test' }],
                        max_tokens: 10
                      })
                    });
                    
                    if (testResponse.ok) {
                      alert('✅ API Key is valid!');
                    } else {
                      const error = await testResponse.text();
                      alert(`❌ API Key test failed: ${error}`);
                    }
                  } catch (error) {
                    alert(`❌ API Key test error: ${error}`);
                  }
                }}
                className="w-full bg-blue-500/20 hover:bg-blue-500/30 text-blue-200 text-xs"
                size="sm"
              >
                🧪 Test API Key
              </Button>
            )}
          </div>

          {/* Output Preview - Always show container even if empty */}
          <div className="flex-grow flex flex-col min-h-[200px] space-y-3 border border-purple-400/20 rounded-lg p-3 bg-slate-900/30">
            {currentOutputData ? (
              <>
                {/* Quick Stats */}
                <div className="grid grid-cols-3 gap-2 text-xs">
                  <div className="text-center p-2 bg-purple-400/10 rounded">
                    <div className="text-purple-200/70">Model</div>
                    <div className="text-purple-200 font-medium text-xs break-all">{currentOutputData.model || 'N/A'}</div>
                  </div>
                  <div className="text-center p-2 bg-purple-400/10 rounded">
                    <div className="text-purple-200/70">Tokens</div>
                    <div className="text-purple-200 font-medium">{usage?.total_tokens || 'N/A'}</div>
                  </div>
                  <div className="text-center p-2 bg-purple-400/10 rounded">
                    <div className="text-purple-200/70">Cost</div>
                    <div className="text-purple-200 font-medium">${executionCost?.toFixed(4) || 'N/A'}</div>
                  </div>
                </div>

                {/* Generated Content */}
                <div className="flex-grow">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-purple-300 font-medium">Generated Content</span>
                    <span className="text-xs text-purple-200/60">
                      {currentOutputData.content?.length > 200 ? 'Truncated' : 'Full'}
                    </span>
                  </div>
                  <div className="text-xs text-purple-100 font-mono h-full min-h-[8rem] max-h-[16rem] overflow-y-auto break-words whitespace-pre-wrap bg-slate-900/50 rounded p-2">
                    {truncateText(currentOutputData.content || 'No content', 1000)}
                  </div>
                </div>

                {/* Send to Next Node Button */}
                <Button
                  onClick={handleSendToNext}
                  className="w-full bg-green-500/20 hover:bg-green-500/30 text-green-200 border border-green-400/30"
                  disabled={!data.onDataOutput}
                >
                  <Send className="w-4 h-4 mr-2" />
                  Send to Next Node
                </Button>
              </>
            ) : (
              <div className="flex-grow flex items-center justify-center text-purple-200/50 text-sm">
                Execute Groq to see results here
              </div>
            )}
          </div>

          {/* Status Indicator */}
          <div className="flex items-center justify-between text-xs">
            <span className="text-purple-300/80">Groq Llama Processing</span>
            <div className={`w-2 h-2 rounded-full ${
              currentStatus === 'running' ? 'bg-purple-400' :
              currentStatus === 'completed' ? 'bg-green-400' :
              currentStatus === 'error' ? 'bg-red-400' :
              'bg-purple-400/50'
            }`} />
          </div>
        </div>
      </div>

      {/* Connection Handles */}
      <Handle type="target" position={Position.Left} className="w-3 h-3 border-2 border-purple-400 bg-purple-900" />
      <Handle type="source" position={Position.Right} className="w-3 h-3 border-2 border-purple-400 bg-purple-900" />
    </div>
  );
};

export default GroqLlamaNode;
